name: vercel/ncc
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: tool3/ncc@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          src: 'index.js'
      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist/
